export enum EParam {
  ParamAngleX = 'ParamAngleX',
  ParamAngleY = 'ParamAngleY',
  ParamAngleZ = 'ParamAngleZ',
  ParamEyeLOpen = 'ParamEyeLOpen',
  ParamEyeLSmile = 'ParamEyeLSmile',
  ParamEyeROpen = 'ParamEyeROpen',
  ParamEyeRSmile = 'ParamEyeRSmile',
  ParamEyeBallX = 'ParamEyeBallX',
  ParamEyeBallY = 'ParamEyeBallY',
  ParamEyeBallForm = 'ParamEyeBallForm',
  ParamBrowLY = 'ParamBrowLY',
  ParamBrowRY = 'ParamBrowRY',
  ParamBrowLX = 'ParamBrowLX',
  ParamBrowRX = 'ParamBrowRX',
  ParamBrowLAngle = 'ParamBrowLAngle',
  ParamBrowRAngle = 'ParamBrowRAngle',
  ParamBrowLForm = 'ParamBrowLForm',
  ParamBrowRForm = 'ParamBrowRForm',
  ParamMouthForm = 'ParamMouthForm',
  ParamMouthOpenY = 'ParamMouthOpenY',
  ParamCheek = 'ParamCheek',
  ParamBodyAngleX = 'ParamBodyAngleX',
  ParamBodyAngleY = 'ParamBodyAngleY',
  ParamBodyAngleZ = 'ParamBodyAngleZ',
  ParamBreath = 'ParamBreath',
}

export const ParamDef = {
  [EParam.ParamAngleX]: {
    min: -30,
    max: 30,
    default: 0,
  },
  [EParam.ParamAngleY]: {
    min: -30,
    max: 30,
    default: 0,
  },
  [EParam.ParamAngleZ]: {
    min: -30,
    max: 30,
    default: 0,
  },
  [EParam.ParamEyeLOpen]: {
    min: 0,
    max: 1,
    default: 1,
  },
  [EParam.ParamEyeLSmile]: {
    min: 0,
    max: 1,
    default: 1,
  },
  [EParam.ParamEyeROpen]: {
    min: 0,
    max: 1,
    default: 1,
  },
  [EParam.ParamEyeRSmile]: {
    min: 0,
    max: 1,
    default: 1,
  },
  [EParam.ParamEyeBallX]: {
    min: -1,
    max: 1,
    default: 0,
  },
  [EParam.ParamEyeBallY]: {
    min: -1,
    max: 1,
    default: 0,
  },
  [EParam.ParamEyeBallForm]: {
    min: -1,
    max: 1,
    default: 0,
  },
  [EParam.ParamBrowLY]: {
    min: -1,
    max: 1,
    default: 0,
  },
  [EParam.ParamBrowRY]: {
    min: -1,
    max: 1,
    default: 0,
  },
  [EParam.ParamBrowLX]: {
    min: -1,
    max: 1,
    default: 0,
  },
  [EParam.ParamBrowRX]: {
    min: -1,
    max: 1,
    default: 0,
  },
  [EParam.ParamBrowLAngle]: {
    min: -1,
    max: 1,
    default: 0,
  },
  [EParam.ParamBrowRAngle]: {
    min: -1,
    max: 1,
    default: 0,
  },
  [EParam.ParamBrowLForm]: {
    min: -1,
    max: 1,
    default: 0,
  },
  [EParam.ParamBrowRForm]: {
    min: -1,
    max: 1,
    default: 0,
  },
  [EParam.ParamMouthForm]: {
    min: -1,
    max: 1,
    default: 0,
  },
  [EParam.ParamMouthOpenY]: {
    min: 0,
    max: 1,
    default: 0,
  },
  [EParam.ParamCheek]: {
    min: 0,
    max: 1,
    default: 0,
  },
  [EParam.ParamBodyAngleX]: {
    min: -10,
    max: 10,
    default: 0,
  },
  [EParam.ParamBodyAngleY]: {
    min: -10,
    max: 10,
    default: 0,
  },
  [EParam.ParamBodyAngleZ]: {
    min: -10,
    max: 10,
    default: 0,
  },
  [EParam.ParamBreath]: {
    min: 0,
    max: 1,
    default: 1,
  },
};

export const initialPresets = [
  {
    name: 'default',
    state: {
      ParamAngleX: 0,
      ParamAngleY: 0,
      ParamAngleZ: 0,
      ParamEyeLOpen: 1,
      ParamEyeLSmile: 1,
      ParamEyeROpen: 1,
      ParamEyeRSmile: 1,
      ParamEyeBallX: 0,
      ParamEyeBallY: 0,
      ParamEyeBallForm: 0,
      ParamBrowLY: 0,
      ParamBrowRY: 0,
      ParamBrowLX: 0,
      ParamBrowRX: 0,
      ParamBrowLAngle: 0,
      ParamBrowRAngle: 0,
      ParamBrowLForm: 0,
      ParamBrowRForm: 0,
      ParamMouthForm: 0,
      ParamMouthOpenY: 0,
      ParamCheek: 0,
      ParamBodyAngleX: 0,
      ParamBodyAngleY: 0,
      ParamBodyAngleZ: 0,
    },
  },
  {
    name: 'smile closed eyes',
    state: {
      ParamAngleX: 0,
      ParamAngleY: 0,
      ParamAngleZ: 0,
      ParamEyeLOpen: 0,
      ParamEyeLSmile: 1,
      ParamEyeROpen: 0,
      ParamEyeRSmile: 1,
      ParamEyeBallX: 0,
      ParamEyeBallY: 0,
      ParamEyeBallForm: 0,
      ParamBrowLY: 0,
      ParamBrowRY: 0,
      ParamBrowLX: 0,
      ParamBrowRX: 0,
      ParamBrowLAngle: 0,
      ParamBrowRAngle: 0,
      ParamBrowLForm: 0,
      ParamBrowRForm: 0,
      ParamMouthForm: 1,
      ParamMouthOpenY: 0,
      ParamCheek: 0,
      ParamBodyAngleX: 0,
      ParamBodyAngleY: 0,
      ParamBodyAngleZ: 0,
    },
  },
  {
    name: 'laugh closed eye',
    state: {
      ParamAngleX: 0,
      ParamAngleY: 0,
      ParamAngleZ: 0,
      ParamEyeLOpen: 0,
      ParamEyeLSmile: 1,
      ParamEyeROpen: 0,
      ParamEyeRSmile: 1,
      ParamEyeBallX: 0,
      ParamEyeBallY: 0,
      ParamEyeBallForm: 0,
      ParamBrowLY: 0,
      ParamBrowRY: 0,
      ParamBrowLX: 0,
      ParamBrowRX: 0,
      ParamBrowLAngle: 0,
      ParamBrowRAngle: 0,
      ParamBrowLForm: 0,
      ParamBrowRForm: 0,
      ParamMouthForm: 1,
      ParamMouthOpenY: 0.8,
      ParamCheek: 0,
      ParamBodyAngleX: 0,
      ParamBodyAngleY: 0,
      ParamBodyAngleZ: 0,
    },
  },
  {
    name: 'laughe open eyes',
    state: {
      ParamAngleX: 0,
      ParamAngleY: 0,
      ParamAngleZ: 0,
      ParamEyeLOpen: 1,
      ParamEyeLSmile: 1,
      ParamEyeROpen: 1,
      ParamEyeRSmile: 1,
      ParamEyeBallX: 0,
      ParamEyeBallY: 0,
      ParamEyeBallForm: 0,
      ParamBrowLY: 0,
      ParamBrowRY: 0,
      ParamBrowLX: 0,
      ParamBrowRX: 0,
      ParamBrowLAngle: 0,
      ParamBrowRAngle: 0,
      ParamBrowLForm: 0,
      ParamBrowRForm: 0,
      ParamMouthForm: 1,
      ParamMouthOpenY: 0.8,
      ParamCheek: 0,
      ParamBodyAngleX: 0,
      ParamBodyAngleY: 0,
      ParamBodyAngleZ: 0,
    },
  },
  {
    name: 'smile open eye',
    state: {
      ParamAngleX: 0,
      ParamAngleY: 0,
      ParamAngleZ: 0,
      ParamEyeLOpen: 1,
      ParamEyeLSmile: 1,
      ParamEyeROpen: 1,
      ParamEyeRSmile: 1,
      ParamEyeBallX: 0,
      ParamEyeBallY: 0,
      ParamEyeBallForm: 0,
      ParamBrowLY: 0,
      ParamBrowRY: 0,
      ParamBrowLX: 0,
      ParamBrowRX: 0,
      ParamBrowLAngle: 0,
      ParamBrowRAngle: 0,
      ParamBrowLForm: 0,
      ParamBrowRForm: 0,
      ParamMouthForm: 1,
      ParamMouthOpenY: 0,
      ParamCheek: 0,
      ParamBodyAngleX: 0,
      ParamBodyAngleY: 0,
      ParamBodyAngleZ: 0,
    },
  },
  {
    name: 'look right',
    state: {
      ParamAngleX: -30,
      ParamAngleY: 0,
      ParamAngleZ: 0,
      ParamEyeLOpen: 1,
      ParamEyeLSmile: 1,
      ParamEyeROpen: 1,
      ParamEyeRSmile: 1,
      ParamEyeBallX: 0,
      ParamEyeBallY: 0,
      ParamEyeBallForm: 0,
      ParamBrowLY: 0,
      ParamBrowRY: 0,
      ParamBrowLX: 0,
      ParamBrowRX: 0,
      ParamBrowLAngle: 0,
      ParamBrowRAngle: 0,
      ParamBrowLForm: 0,
      ParamBrowRForm: 0,
      ParamMouthForm: 1,
      ParamMouthOpenY: 0,
      ParamCheek: 0,
      ParamBodyAngleX: 0,
      ParamBodyAngleY: 0,
      ParamBodyAngleZ: 0,
    },
  },
  {
    name: 'look left',
    state: {
      ParamAngleX: 30,
      ParamAngleY: 0,
      ParamAngleZ: 0,
      ParamEyeLOpen: 1,
      ParamEyeLSmile: 1,
      ParamEyeROpen: 1,
      ParamEyeRSmile: 1,
      ParamEyeBallX: 0,
      ParamEyeBallY: 0,
      ParamEyeBallForm: 0,
      ParamBrowLY: 0,
      ParamBrowRY: 0,
      ParamBrowLX: 0,
      ParamBrowRX: 0,
      ParamBrowLAngle: 0,
      ParamBrowRAngle: 0,
      ParamBrowLForm: 0,
      ParamBrowRForm: 0,
      ParamMouthForm: 1,
      ParamMouthOpenY: 0,
      ParamCheek: 0,
      ParamBodyAngleX: 0,
      ParamBodyAngleY: 0,
      ParamBodyAngleZ: 0,
    },
  },
  {
    name: 'look up',
    state: {
      ParamAngleX: 0,
      ParamAngleY: 30,
      ParamAngleZ: 0,
      ParamEyeLOpen: 1,
      ParamEyeLSmile: 1,
      ParamEyeROpen: 1,
      ParamEyeRSmile: 1,
      ParamEyeBallX: 0,
      ParamEyeBallY: 1,
      ParamEyeBallForm: 0,
      ParamBrowLY: 0,
      ParamBrowRY: 0,
      ParamBrowLX: 0,
      ParamBrowRX: 0,
      ParamBrowLAngle: 0,
      ParamBrowRAngle: 0,
      ParamBrowLForm: 0,
      ParamBrowRForm: 0,
      ParamMouthForm: 1,
      ParamMouthOpenY: 0,
      ParamCheek: 0,
      ParamBodyAngleX: 0,
      ParamBodyAngleY: 0,
      ParamBodyAngleZ: 0,
    },
  },
  {
    name: 'look down',
    state: {
      ParamAngleX: 0,
      ParamAngleY: -30,
      ParamAngleZ: 0,
      ParamEyeLOpen: 1,
      ParamEyeLSmile: 1,
      ParamEyeROpen: 1,
      ParamEyeRSmile: 1,
      ParamEyeBallX: 0,
      ParamEyeBallY: -1,
      ParamEyeBallForm: 0,
      ParamBrowLY: 0,
      ParamBrowRY: 0,
      ParamBrowLX: 0,
      ParamBrowRX: 0,
      ParamBrowLAngle: 0,
      ParamBrowRAngle: 0,
      ParamBrowLForm: 0,
      ParamBrowRForm: 0,
      ParamMouthForm: 1,
      ParamMouthOpenY: 0,
      ParamCheek: 0,
      ParamBodyAngleX: 0,
      ParamBodyAngleY: 0,
      ParamBodyAngleZ: 0,
    },
  },
  {
    name: 'sad',
    state: {
      ParamAngleX: 0,
      ParamAngleY: 0,
      ParamAngleZ: 0,
      ParamEyeLOpen: 0.85,
      ParamEyeLSmile: 0,
      ParamEyeROpen: 0.9,
      ParamEyeRSmile: 0,
      ParamEyeBallX: 0,
      ParamEyeBallY: 0,
      ParamEyeBallForm: 0,
      ParamBrowLY: 0,
      ParamBrowRY: 0,
      ParamBrowLX: 0,
      ParamBrowRX: 0,
      ParamBrowLAngle: 0,
      ParamBrowRAngle: 0,
      ParamBrowLForm: -1,
      ParamBrowRForm: -1,
      ParamMouthForm: -1,
      ParamMouthOpenY: 0,
      ParamCheek: 0,
      ParamBodyAngleX: 0,
      ParamBodyAngleY: 10,
      ParamBodyAngleZ: 0,
    },
  },
  {
    name: 'surprised',
    state: {
      ParamAngleX: 0,
      ParamAngleY: 0,
      ParamAngleZ: 0,
      ParamEyeLOpen: 1,
      ParamEyeLSmile: 1,
      ParamEyeROpen: 1,
      ParamEyeRSmile: 0.45,
      ParamEyeBallX: 0,
      ParamEyeBallY: 0.1,
      ParamEyeBallForm: -0.1,
      ParamBrowLY: 0,
      ParamBrowRY: 0,
      ParamBrowLX: 0,
      ParamBrowRX: 0,
      ParamBrowLAngle: 0.7,
      ParamBrowRAngle: 0.3,
      ParamBrowLForm: 1,
      ParamBrowRForm: 1,
      ParamMouthForm: -1,
      ParamMouthOpenY: 1,
      ParamCheek: 0,
      ParamBodyAngleX: 0,
      ParamBodyAngleY: 0,
      ParamBodyAngleZ: 0,
    },
  },
  {
    name: 'left turn',
    state: {
      ParamAngleX: 0,
      ParamAngleY: 0,
      ParamAngleZ: 0,
      ParamEyeLOpen: 1,
      ParamEyeLSmile: 1,
      ParamEyeROpen: 1,
      ParamEyeRSmile: 1,
      ParamEyeBallX: 0,
      ParamEyeBallY: 0,
      ParamEyeBallForm: 0,
      ParamBrowLY: 0,
      ParamBrowRY: 0,
      ParamBrowLX: 0,
      ParamBrowRX: 0,
      ParamBrowLAngle: 0,
      ParamBrowRAngle: 0,
      ParamBrowLForm: 0,
      ParamBrowRForm: 0,
      ParamMouthForm: 0,
      ParamMouthOpenY: 0,
      ParamCheek: 0,
      ParamBodyAngleX: 10,
      ParamBodyAngleY: 0,
      ParamBodyAngleZ: 0,
    },
  },
  {
    name: 'right turn',
    state: {
      ParamAngleX: 0,
      ParamAngleY: 0,
      ParamAngleZ: 0,
      ParamEyeLOpen: 1,
      ParamEyeLSmile: 1,
      ParamEyeROpen: 1,
      ParamEyeRSmile: 1,
      ParamEyeBallX: 0,
      ParamEyeBallY: 0,
      ParamEyeBallForm: 0,
      ParamBrowLY: 0,
      ParamBrowRY: 0,
      ParamBrowLX: 0,
      ParamBrowRX: 0,
      ParamBrowLAngle: 0,
      ParamBrowRAngle: 0,
      ParamBrowLForm: 0,
      ParamBrowRForm: 0,
      ParamMouthForm: 0,
      ParamMouthOpenY: 0,
      ParamCheek: 0,
      ParamBodyAngleX: -10,
      ParamBodyAngleY: 0,
      ParamBodyAngleZ: 0,
    },
  },
  {
    name: 'left tint',
    state: {
      ParamAngleX: 0,
      ParamAngleY: 0,
      ParamAngleZ: 0,
      ParamEyeLOpen: 1,
      ParamEyeLSmile: 1,
      ParamEyeROpen: 1,
      ParamEyeRSmile: 1,
      ParamEyeBallX: 0,
      ParamEyeBallY: 0,
      ParamEyeBallForm: 0,
      ParamBrowLY: 0,
      ParamBrowRY: 0,
      ParamBrowLX: 0,
      ParamBrowRX: 0,
      ParamBrowLAngle: 0,
      ParamBrowRAngle: 0,
      ParamBrowLForm: 0,
      ParamBrowRForm: 0,
      ParamMouthForm: 0,
      ParamMouthOpenY: 0,
      ParamCheek: 0,
      ParamBodyAngleX: -10,
      ParamBodyAngleY: 0,
      ParamBodyAngleZ: 10,
    },
  },
  {
    name: 'right tint',
    state: {
      ParamAngleX: 0,
      ParamAngleY: 0,
      ParamAngleZ: 0,
      ParamEyeLOpen: 1,
      ParamEyeLSmile: 1,
      ParamEyeROpen: 1,
      ParamEyeRSmile: 1,
      ParamEyeBallX: 0,
      ParamEyeBallY: 0,
      ParamEyeBallForm: 0,
      ParamBrowLY: 0,
      ParamBrowRY: 0,
      ParamBrowLX: 0,
      ParamBrowRX: 0,
      ParamBrowLAngle: 0,
      ParamBrowRAngle: 0,
      ParamBrowLForm: 0,
      ParamBrowRForm: 0,
      ParamMouthForm: 0,
      ParamMouthOpenY: 0,
      ParamCheek: 0,
      ParamBodyAngleX: -10,
      ParamBodyAngleY: 0,
      ParamBodyAngleZ: -10,
    },
  },
];
